import { ArrowLeft, BookOpen, CircleAlert, FileKey2, Landmark, Link2, ScrollText } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import type { CandidateBankLink, EvidenceLink } from "../../types/api";
import { AuditDrawer } from "../../components/AuditDrawer";
import { CopyList, CopyValue, EmptyState, ErrorState, EvidenceBadge, CalculatedValues, Loading, ReasonCodes, StateBadge } from "../../components/ui";
import { formatSubunits } from "../../lib/format";
import { reasonLabel } from "../../lib/labels";
import { useSettlement } from "../../lib/queries";

export function SettlementDetailPage() {
  const { batchId, settlementId } = useParams();
  const navigate = useNavigate();
  const query = useSettlement(batchId, settlementId);
  if (query.isLoading) return <Loading />;
  if (query.isError || !query.data) return <ErrorState error={query.error ?? new Error("Settlement evidence unavailable.")} onRetry={() => void query.refetch()} />;
  const item = query.data; const aggregate = item.aggregate;
  const bank = item.accepted_evidence_links.find((link) => link.relationship_type === "settlement_to_bank");
  const ledger = item.accepted_evidence_links.filter((link) => link.relationship_type === "gateway_to_ledger");
  return <div id="main-content" className="space-y-5"><button className="inline-flex items-center gap-2 text-sm font-bold text-teal hover:underline" type="button" onClick={() => navigate(`/batches/${batchId}/settlements`)}><ArrowLeft size={16} /> Settlements</button><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.16em] text-teal">Settlement evidence</p><h1 className="font-serif text-4xl sm:text-5xl">{aggregate.settlement_id}</h1><p className="mt-3 text-sm text-muted">{aggregate.balance_account_id ?? "No balance-account partition"} · settled {new Date(aggregate.latest_settled_at).toLocaleDateString("en-IN", { timeZone: "UTC" })}</p></div><div className="flex flex-wrap items-center gap-2"><StateBadge state={item.state} /><AuditDrawer batchId={batchId!} settlementId={settlementId} trigger={<><ScrollText size={15} /> Explain decision</>} /></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Signed net", formatSubunits(aggregate.signed_net.subunits), "authoritative: total credit − total debit"], ["Gross activity", formatSubunits(aggregate.gross_activity_subunits), ""], ["Fee / tax", formatSubunits(aggregate.total_fee_subunits + aggregate.total_tax_subunits), `${formatSubunits(aggregate.total_fee_subunits)} fee · ${formatSubunits(aggregate.total_tax_subunits)} tax`], ["Unresolved", formatSubunits(item.unresolved_value_subunits), ""]].map(([label, value, note]) => <div className="border border-line bg-panel p-4" key={label}><span className="text-xs font-bold uppercase tracking-[0.1em] text-muted">{label}</span><strong className="mt-3 block font-serif text-2xl">{value}</strong>{note && <small className="mt-1 block text-xs text-muted">{note}</small>}</div>)}</div>
    <section className="border border-line bg-panel p-5 sm:p-7" aria-labelledby="flow-title"><PanelHeading eyebrow="Movement-level proof" title="Razorpay → Bank → Ledger"><Link2 size={21} aria-hidden="true" /></PanelHeading><div className="mt-6 grid gap-3 lg:grid-cols-3"><FlowColumn title="Razorpay" icon={<FileKey2 />}><p><strong>{aggregate.member_entity_ids.length}</strong> gateway movements</p><p><strong>{aggregate.total_credit_subunits > 0 ? formatSubunits(aggregate.total_credit_subunits) : "—"}</strong> credit activity</p><p className="break-all font-mono text-xs">{aggregate.normalized_utrs.length ? aggregate.normalized_utrs.join(", ") : "No UTR"}</p><p>{aggregate.utr_conflict ? "UTR conflict detected" : "UTR set is consistent"}</p><div className="mt-3"><p className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-muted">Gateway source records</p><CopyList values={aggregate.member_source_record_ids} /></div></FlowColumn><FlowColumn title="Bank" icon={<Landmark />}><EvidenceRelation link={bank} empty="No verified settlement-level bank evidence" /></FlowColumn><FlowColumn title="Ledger" icon={<BookOpen />}><p><strong>{ledger.length}</strong> verified movement links</p><p>{item.accounting_control?.complete_evidence ? "Journal controls complete" : "Journal controls open"}</p><p>Clearing residual <strong>{formatSubunits(item.accounting_control?.clearing_residual.subunits ?? 0)}</strong></p><p className="break-all font-mono text-xs">{item.accounting_control?.settlement_posting_journal_id ?? "No settlement posting journal"}</p></FlowColumn></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><div className="border border-line bg-panel p-5 sm:p-7"><PanelHeading eyebrow="Evidence relationships" title="Accepted, proposed, rejected"><Link2 size={20} aria-hidden="true" /></PanelHeading><p className="mt-2 text-sm leading-6 text-muted">Every relationship retains its status, lineage, calculations, candidate signals, and decision citations. Expand a row for the complete evidence record.</p><div className="mt-5 space-y-3">{item.accepted_evidence_links.map((link) => <EvidenceCard key={link.link_id} link={link} status="verified" />)}{item.proposed_evidence_links.map((link) => <EvidenceCard key={link.link_id} link={link} status="proposed" />)}{item.rejected_candidates.map((candidate) => <CandidateCard key={`${candidate.bank_source_record_id}:${candidate.bank_row_id}`} candidate={candidate} />)}{!item.accepted_evidence_links.length && !item.proposed_evidence_links.length && !item.rejected_candidates.length && <EmptyState title="No relationship records">The API returned no accepted, proposed, or rejected relationship evidence for this settlement.</EmptyState>}</div></div>
      <div className="space-y-5"><div className="border border-line bg-panel p-5 sm:p-7"><PanelHeading eyebrow="Accounting controls" title="Control checks"><CircleAlert size={20} aria-hidden="true" /></PanelHeading>{item.accounting_control ? <><div className="mt-5 grid gap-2">{[["Movement evidence", `${item.accounting_control.movement_evidence.filter((movement) => movement.status === "verified").length} verified`], ["Settlement posting", item.accounting_control.missing_settlement_posting ? "Missing" : "Verified"], ["Duplicate lines", item.accounting_control.duplicate_line_ids.length.toString()], ["Journal balance", item.accounting_control.journal_unbalanced_ids.length ? "Unbalanced" : "Balanced"], ["Clearing residual", formatSubunits(item.accounting_control.clearing_residual.subunits)]].map(([label, value]) => <div className="flex items-center justify-between gap-3 border-b border-line py-2 text-sm last:border-0" key={label}><span className="text-muted">{label}</span><strong>{value}</strong></div>)}</div><div className="mt-5"><p className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-muted">Control source IDs</p><CopyList values={[...item.accounting_control.linked_ledger_source_record_ids, ...item.accounting_control.settlement_posting_source_record_ids, ...item.accounting_control.duplicate_line_ids, ...item.accounting_control.journal_unbalanced_ids]} /></div>{item.accounting_control.reasons.length > 0 && <div className="mt-5"><ReasonCodes codes={item.accounting_control.reasons} /></div>}</> : <EmptyState title="No accounting control record">The API did not return controls for this settlement.</EmptyState>}</div>
        <div className="border border-line bg-panel p-5 sm:p-7"><PanelHeading eyebrow="Decision provenance" title="Why this state"><FileKey2 size={20} aria-hidden="true" /></PanelHeading><div className="mt-5"><ReasonCodes codes={item.reason_codes} /></div><dl className="mt-5 grid gap-4"><Meta label="Decision ID"><CopyValue value={item.decision.decision_id} label="Copy decision ID" /></Meta><Meta label="Rule / version"><span className="font-mono text-xs">{item.decision.rule_id} / {item.decision.rule_version}</span></Meta><Meta label="Policy / schema"><span className="font-mono text-xs">{item.decision.policy_version} / {item.decision.schema_version}</span></Meta><Meta label="Evaluation clock"><span className="font-mono text-xs">{item.decision.evaluation_clock}</span></Meta><Meta label="Decision-cited source IDs"><CopyList values={item.decision.cited_source_record_ids} /></Meta><Meta label="Decision input fingerprints"><CopyList values={item.decision.input_fingerprints} label="Copy input fingerprint" /></Meta><div><dt className="text-xs text-muted">Calculated values</dt><dd className="mt-2"><CalculatedValues values={item.decision.calculated_values} /></dd></div></dl></div></div>
    </section>
    {item.exceptions.length > 0 && <section className="border border-line bg-panel p-5 sm:p-7"><PanelHeading eyebrow="Associated exceptions" title="Exceptions cited by this settlement"><CircleAlert size={20} aria-hidden="true" /></PanelHeading><div className="mt-5 space-y-3">{item.exceptions.map((exception) => <div className="border border-line bg-paper p-4" key={exception.exception_id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{reasonLabel(exception.reason_code)}</strong><p className="mt-1 text-sm text-muted">{exception.explanation}</p></div><strong className="font-mono">{formatSubunits(exception.value_subunits)}</strong></div><div className="mt-3"><p className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-muted">Cited source IDs — each copyable</p><CopyList values={exception.source_record_ids} /></div></div>)}</div></section>}
    <p className="text-xs leading-5 text-muted">Full relationship provenance is available in the expandable records above. Proposed and rejected evidence is deliberately styled separately from verified evidence.</p>
  </div>;
}

function FlowColumn({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <div className="border border-line bg-paper p-4"><div className="mb-4 flex items-center gap-2 text-teal">{icon}<h3 className="font-bold text-ink">{title}</h3></div><div className="space-y-2 text-sm leading-6">{children}</div></div>; }
function EvidenceRelation({ link, empty }: { link: EvidenceLink | undefined; empty: string }) { return link ? <div className="space-y-3"><EvidenceBadge status="verified" /><p className="font-bold capitalize">{link.relationship_type.replaceAll("_", " ")}</p><p className="text-sm text-muted">Link ID <span className="font-mono">{link.link_id}</span></p><p className="font-mono text-sm">score {link.candidate_score ?? "n/a"}</p><CopyList values={link.source_record_ids} /></div> : <p className="text-sm text-muted">{empty}</p>; }
function EvidenceCard({ link, status }: { link: EvidenceLink; status: "verified" | "proposed" }) { return <details className="border border-line bg-paper"><summary className="cursor-pointer list-none p-4 hover:bg-white"><div className="flex flex-wrap items-center gap-2"><EvidenceBadge status={status} /><strong className="capitalize">{link.relationship_type.replaceAll("_", " ")}</strong><span className="font-mono text-xs text-muted">{link.link_id}</span></div><p className="mt-2 text-sm text-muted">{link.source_record_ids.length} source records · {link.journal_id ? `journal ${link.journal_id}` : "no journal ID"}</p></summary><div className="space-y-4 border-t border-line p-4"><Meta label="Link ID"><CopyValue value={link.link_id} label="Copy link ID" /></Meta><Meta label="Relationship type"><span className="font-mono text-xs">{link.relationship_type}</span></Meta><Meta label="Status"><EvidenceBadge status={status} /></Meta><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-muted">Exact source record IDs</p><CopyList values={link.source_record_ids} /></div><div className="grid gap-3 sm:grid-cols-2"><Meta label="Gateway source record ID">{link.gateway_source_record_id ? <CopyValue value={link.gateway_source_record_id} label="Copy gateway source record ID" /> : "—"}</Meta><Meta label="Journal ID">{link.journal_id ? <CopyValue value={link.journal_id} label="Copy journal ID" /> : "—"}</Meta><Meta label="Candidate score"><span className="font-mono text-xs">{link.candidate_score ?? "—"}</span></Meta></div><ReasonCodes codes={link.reason_codes} /><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-muted">Calculated values</p><CalculatedValues values={link.calculated_values} /></div><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-muted">Candidate signals</p><div className="flex flex-wrap gap-2">{link.candidate_signals.length ? link.candidate_signals.map((signal) => <span className={`rounded border px-2 py-1 text-xs ${signal.satisfied ? "border-sage/30 bg-sage/10 text-sage" : "border-coral/30 bg-coral/10 text-coral"}`} key={signal.name}>{signal.name}: {signal.value} · weight {signal.weight}</span>) : <span className="text-sm text-muted">None</span>}</div></div></div></details>; }
function CandidateCard({ candidate }: { candidate: CandidateBankLink }) { return <details className="border border-coral/30 bg-coral/5"><summary className="cursor-pointer list-none p-4"><div className="flex flex-wrap items-center gap-2"><EvidenceBadge status="rejected" /><strong>Rejected bank candidate</strong><span className="font-mono text-xs text-muted">score {candidate.score}</span></div><p className="mt-2 text-sm text-muted">{candidate.bank_row_id} · {candidate.bank_source_record_id}</p></summary><div className="space-y-4 border-t border-coral/20 p-4"><Meta label="Relationship status"><EvidenceBadge status="rejected" /></Meta><Meta label="Settlement / aggregate"><span className="font-mono text-xs">{candidate.settlement_id} / {candidate.settlement_aggregate_id}</span></Meta><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-muted">Exact candidate source IDs</p><CopyList values={[candidate.bank_source_record_id, candidate.bank_row_id]} /></div><Meta label="Candidate score"><span className="font-mono text-xs">{candidate.score}</span></Meta><ReasonCodes codes={candidate.rejection_reasons} /><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-muted">Candidate signals</p><div className="flex flex-wrap gap-2">{candidate.signals.length ? candidate.signals.map((signal) => <span className={`rounded border px-2 py-1 text-xs ${signal.satisfied ? "border-sage/30 bg-sage/10 text-sage" : "border-coral/30 bg-coral/10 text-coral"}`} key={signal.name}>{signal.name}: {signal.value} · weight {signal.weight}</span>) : <span className="text-sm text-muted">None</span>}</div></div></div></details>; }
function Meta({ label, children }: { label: string; children: React.ReactNode }) { return <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1">{children}</dd></div>; }
function PanelHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div className="flex items-start justify-between gap-4"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[0.16em] text-teal">{eyebrow}</p><h2 className="font-serif text-2xl">{title}</h2></div><span className="text-teal">{children}</span></div>; }
