import { ArrowRight, CircleAlert, FileText, Gauge, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import type { ResolutionState } from "../../types/api";
import { useResult } from "../../lib/queries";
import { formatBytes, formatDate, formatSubunits } from "../../lib/format";
import { READINESS_LABELS } from "../../lib/labels";
import { CopyValue, ErrorState, Loading, ReadinessBanner, StateBadge } from "../../components/ui";

const METRIC_CLASSES = { verified: "border-sage/40 bg-sage/5", explained: "border-teal/40 bg-teal/5", pending: "border-amber/40 bg-amber/5", unresolved: "border-coral/40 bg-coral/5", total: "border-line bg-panel" } as const;

export function OverviewPage() {
  const { batchId } = useParams();
  const query = useResult(batchId);
  if (query.isLoading) return <Loading />;
  if (query.isError || !query.data) return <ErrorState error={query.error ?? new Error("The completed result is unavailable.")} onRetry={() => void query.refetch()} />;
  const result = query.data;
  const readiness = result.close_readiness;
  const stateCounts = result.settlements.reduce<Partial<Record<ResolutionState, number>>>((counts, item) => { counts[item.state] = (counts[item.state] ?? 0) + 1; return counts; }, {});
  const blocking = result.exceptions.filter((item) => item.blocking).length;
  const permitted = result.exceptions.filter((item) => !item.blocking).length;
  const metrics = [["Verified value", readiness.verified_value_subunits, "verified"], ["Explained value", readiness.explained_value_subunits, "explained"], ["Pending value", readiness.pending_value_subunits, "pending"], ["Unresolved value", readiness.unresolved_value_subunits, "unresolved"], ["Total absolute value", readiness.batch_total_abs_value_subunits, "total"]] as const;
  return <div id="main-content" className="space-y-5"><PageHeader eyebrow="Close readiness" title="Can this batch close?" description={`A deterministic assessment of ${result.settlements.length} settlements at ${formatDate(result.evaluation_clock)}.`} action={<Link className="inline-flex items-center gap-2 rounded-sm border border-line bg-panel px-4 py-2.5 text-sm font-bold text-teal hover:border-teal" to={`/batches/${batchId}/exceptions`}>Review exceptions <ArrowRight size={16} /></Link>} /><ReadinessBanner readiness={readiness.readiness} counts={`${blocking} blocking · ${permitted} permitted exceptions`} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label, value, kind]) => <div className={`border p-4 ${METRIC_CLASSES[kind]}`} key={label}><span className="text-xs font-bold uppercase tracking-[0.1em] text-muted">{label}</span><strong className="mt-3 block font-serif text-2xl">{formatSubunits(value)}</strong><small className="mt-1 block text-xs text-muted">{kind === "unresolved" ? "requires attention" : "integer subunits · INR"}</small></div>)}</div>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><div className="border border-line bg-panel p-5 sm:p-7"><PanelHeading eyebrow="What the controls say" title="Resolution coverage"><Gauge size={20} aria-hidden="true" /></PanelHeading><div className="mt-6 space-y-4">{Object.entries(stateCounts).sort().map(([state, count]) => <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3" key={state}><StateBadge state={state as ResolutionState} /><strong>{count}</strong><div className="col-span-2 h-2 overflow-hidden rounded-full bg-paper"><div className="h-full rounded-full bg-teal" style={{ width: `${(count / Math.max(1, result.settlements.length)) * 100}%` }} /></div></div>)}</div><div className="mt-7 flex gap-3 border-t border-line pt-5 text-sm"><CircleAlert size={18} className="shrink-0 text-teal" aria-hidden="true" /><div><strong>{readiness.readiness === "BLOCKED" ? "Resolve every blocking exception before close." : readiness.readiness === "READY" ? "No blocking control is open." : "Review the permitted exceptions in the proof packet."}</strong><p className="mt-1 leading-6 text-muted">{READINESS_LABELS[readiness.readiness]} is derived by the versioned close policy; Vouch does not offer a client-side override.</p></div></div></div>
      <div className="border border-line bg-panel p-5 sm:p-7"><PanelHeading eyebrow="Provenance" title="Inputs and rules"><FileText size={20} aria-hidden="true" /></PanelHeading><dl className="mt-6 space-y-4">{[<div key="clock"><dt className="text-xs text-muted">Evaluation clock</dt><dd className="mt-1 font-mono text-xs">{result.evaluation_clock}</dd></div>, <div key="versions"><dt className="text-xs text-muted">Schema / rule</dt><dd className="mt-1 font-mono text-xs">{result.schema_version} / {result.rule_version}</dd></div>, <div key="policy"><dt className="text-xs text-muted">Policy</dt><dd className="mt-1 font-mono text-xs">{result.policy_version}</dd></div>, ...result.source_fingerprints.map((source) => <div key={source.source_kind}><dt className="text-xs text-muted">{source.source_name}<small className="ml-2">{formatBytes(source.byte_count)}</small></dt><dd className="mt-1"><CopyValue value={source.sha256} label={`Copy ${source.source_name} fingerprint`} /></dd></div>)]}</dl></div>
    </section>
    <section className="border border-line bg-panel p-5 sm:p-7"><PanelHeading eyebrow="Source intake" title="Every source row accounted for"><ShieldCheck size={20} aria-hidden="true" /></PanelHeading><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{result.ingestion.map((item) => <div className="border border-line bg-paper p-4" key={item.source_kind}><strong className="block">{item.source_name}</strong><span className="mt-2 block text-sm">{item.accepted_row_count} accepted / {item.row_count} rows</span><small className="mt-1 block text-xs text-muted">{item.rejected_row_count ? `${item.rejected_row_count} rejected evidence rows` : "No rejected rows"}</small></div>)}</div></section>
  </div>;
}

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.16em] text-teal">{eyebrow}</p><h1 className="font-serif text-4xl sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{description}</p></div>{action}</div>; }
function PanelHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div className="flex items-start justify-between gap-4"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[0.16em] text-teal">{eyebrow}</p><h2 className="font-serif text-2xl">{title}</h2></div><span className="text-teal">{children}</span></div>; }
